-- MySQL Script generated by MySQL Workbench
-- Sex 07 Out 2016 15:41:17 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mbdsas_repository
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mbdsas_repository
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbdsas_repository` DEFAULT CHARACTER SET latin1 ;
USE `mbdsas_repository` ;

-- -----------------------------------------------------
-- Table `mbdsas_repository`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbdsas_repository`.`language` ;

CREATE TABLE IF NOT EXISTS `mbdsas_repository`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `vendor` VARCHAR(45) NULL COMMENT '',
  `revision` VARCHAR(45) NULL COMMENT '',
  `descr` TEXT NULL COMMENT '',
  `last_updated` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbdsas_repository`.`extension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbdsas_repository`.`extension` ;

CREATE TABLE IF NOT EXISTS `mbdsas_repository`.`extension` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `extension` VARCHAR(45) NOT NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  `vendor` VARCHAR(45) NULL COMMENT '',
  `revision` VARCHAR(45) NULL COMMENT '',
  `descr` TEXT NULL COMMENT '',
  `last_updated` DATETIME NULL COMMENT '',
  `id_language` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_extension_language1_idx` (`id_language` ASC)  COMMENT '',
  UNIQUE INDEX `extension_UNIQUE` (`extension` ASC)  COMMENT '',
  CONSTRAINT `fk_extension_language1`
    FOREIGN KEY (`id_language`)
    REFERENCES `mbdsas_repository`.`language` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbdsas_repository`.`script`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbdsas_repository`.`script` ;

CREATE TABLE IF NOT EXISTS `mbdsas_repository`.`script` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `owner` VARCHAR(100) NULL COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `source` VARCHAR(255) NULL COMMENT '',
  `admin_status` VARCHAR(45) NULL COMMENT '',
  `oper_status` VARCHAR(45) NULL COMMENT '',
  `storage_type` VARCHAR(255) NULL COMMENT '',
  `row_status` VARCHAR(100) NULL COMMENT '',
  `error` VARCHAR(150) NULL COMMENT '',
  `last_updated` DATETIME NULL COMMENT '',
  `descr` TEXT NULL COMMENT '',
  `id_language` INT NOT NULL COMMENT '',
  `code_identifier` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_script_language1_idx` (`id_language` ASC)  COMMENT '',
  UNIQUE INDEX `identifier_UNIQUE` (`code_identifier` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  CONSTRAINT `fk_script_language1`
    FOREIGN KEY (`id_language`)
    REFERENCES `mbdsas_repository`.`language` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbdsas_repository`.`code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbdsas_repository`.`code` ;

CREATE TABLE IF NOT EXISTS `mbdsas_repository`.`code` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `path` TEXT NULL COMMENT '',
  `row_status` VARCHAR(100) NULL COMMENT '',
  `id_script` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_code_script1_idx` (`id_script` ASC)  COMMENT '',
  CONSTRAINT `fk_code_script1`
    FOREIGN KEY (`id_script`)
    REFERENCES `mbdsas_repository`.`script` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbdsas_repository`.`md_filter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbdsas_repository`.`md_filter` ;

CREATE TABLE IF NOT EXISTS `mbdsas_repository`.`md_filter` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `attribute` VARCHAR(45) NULL COMMENT '',
  `value` VARCHAR(45) NULL COMMENT '',
  `operator` VARCHAR(45) NULL COMMENT '',
  `last_updated` DATETIME NULL COMMENT '',
  `id_script` INT NOT NULL COMMENT '',
  `identifier` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `id_script`)  COMMENT '',
  INDEX `fk_md_filter_script1_idx` (`id_script` ASC)  COMMENT '',
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC)  COMMENT '',
  CONSTRAINT `fk_md_filter_script1`
    FOREIGN KEY (`id_script`)
    REFERENCES `mbdsas_repository`.`script` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
