-- MySQL Script generated by MySQL Workbench
-- Sex 23 Set 2016 13:50:25 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mbdsas_mlm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mbdsas_mlm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbdsas_mlm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mbdsas_mlm` ;

-- -----------------------------------------------------
-- Table `mbdsas_mlm`.`md`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbdsas_mlm`.`md` (
  `id` INT NOT NULL COMMENT '',
  `chassis_id_subtype` VARCHAR(50) NULL COMMENT '',
  `chassis_id` VARCHAR(60) NULL COMMENT '',
  `port_id_subtype` VARCHAR(50) NULL COMMENT '',
  `port_desc` TEXT NULL COMMENT '',
  `sys_name` VARCHAR(100) NULL COMMENT '',
  `sys_desc` TEXT NULL COMMENT '',
  `sys_cap_supported` VARCHAR(80) NULL COMMENT '',
  `sys_cap_enabled` VARCHAR(80) NULL COMMENT '',
  `man_addr_entry` VARCHAR(45) NULL COMMENT '',
  `connect_time` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
